// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCGamesPartials.Data;

#nullable disable

namespace PCGamesPartials.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250623160822_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PCGamesPartials.Models.PCGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PCGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Futuristisk open-world shooter.",
                            Genre = "RPG",
                            ImageUrl = "/images/cyberpunk.jpg",
                            Price = 599m,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fantasyvärld med tuffa bossar.",
                            Genre = "Action RPG",
                            ImageUrl = "/images/eldenring.jpg",
                            Price = 699m,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Taktisk 5v5 shooter.",
                            Genre = "FPS",
                            ImageUrl = "/images/valorant.jpg",
                            Price = 0m,
                            Title = "Valorant"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Episkt äventyr med Geralt.",
                            Genre = "RPG",
                            ImageUrl = "/images/witcher3.jpg",
                            Price = 299m,
                            Title = "The Witcher 3"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Klassisk tävlingsskjutare.",
                            Genre = "FPS",
                            ImageUrl = "/images/cs2.jpg",
                            Price = 0m,
                            Title = "CS2"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bygg, utforska, överlev.",
                            Genre = "Sandbox",
                            ImageUrl = "/images/minecraft.jpg",
                            Price = 269m,
                            Title = "Minecraft"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
